apiVersion: apps/v1
kind: Deployment
metadata:
  name: pass-image-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pass-image-api
  template:
    metadata:
      annotations:
        # This will be picked up over OTLP, so we don't need 
        # to have the agent collect it directly.
        # TODO - remove this comment once we're sure everything's going over OTLP
        # ad.datadoghq.com/logs_exclude: "true"
      labels:
        app: pass-image-api
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: pass-image-api
          image: ghcr.io/datadog/sdlc-gitops-sample-stack/pass-image-api:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
          env:
            - name: DD_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: pass-image-api-config
                  key: DD_ENVIRONMENT
            - name: DD_VERSION
              valueFrom:
                configMapKeyRef:
                  name: pass-image-api-config
                  key: DD_VERSION
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: pass-image-api-config
                  key: DD_SERVICE
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=$(DD_ENVIRONMENT),service.version=$(DD_VERSION)
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4317"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
